apiVersion: v1
kind: Service
metadata:
  name: seeds-remoting
spec:
  clusterIP: None
  ports:
  - port: 2551
    protocol: TCP
    targetPort: 2551
    name: akka-remote
  selector:
    type: sharding-sample-seed
