apiVersion: v1
kind: Service
metadata:
  name: sharding-sample-http
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: akka-http
  selector:
    app: sharding-sample
  type: NodePort
